# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-09-18 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interview_question_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_qestion_group_id', models.CharField(max_length=10, unique=True)),
                ('interview_question_group_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='interview_questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_question_id', models.CharField(max_length=10, unique=True)),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.TextField()),
                ('interview_qestion_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interview_question_group')),
            ],
        ),
    ]
