# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-09-18 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20190919_0143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='interview_answer',
            new_name='InterviewAnswer',
        ),
        migrations.RenameModel(
            old_name='interview_question',
            new_name='InterviewQuestion',
        ),
    ]
